# Preprocessing pipeline configuration

tracking:
  use_multiple_balls: false

merge:
  gap_allowed: 5
  max_d: 50.0

smoothing:
  method: kf_smoothing
  max_missing_sec: 0.5
  process_sigma_bias: 10.0
  process_sigma_slope: 12.0
  obs_std: 0.002
  init_vel_std: 0.05
  ll_diff: 5.0

contact:
  epsilon_frac: 0.66
  out_margin: 5.0
  max_distance_for_contact_approval: 0.55
  min_ball_height_to_detect_high_pivot: 0.17

pivot_point:
  model_checkpoint: checkpoints/pivot_points/pp_v8_new_f3.pickle
  threshold: 0.11
  window: 11
